# Generated by Django 4.2.3 on 2023-07-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0002_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteos',
            old_name='categoría',
            new_name='categoria',
        ),
    ]
